Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -35,13 +35,23 @@ pipeline {
     stage('Build Docker Image from Existing WAR') {
       steps {
         script {
-          sh """
-            echo "Using existing WAR file..."
-            WAR_FILE="taxi-booking/target/taxi-booking-1.0.1.war"
-            echo "Building Docker image..."
-            cp \$WAR_FILE ./ || { echo "WAR file not found!"; exit 1; }
-            docker build -t \${DOCKERHUB_USER}/\${IMAGE_NAME}:${params.IMAGE_TAG} .
-          """
+          // Check if the image exists locally
+          def imageExists = sh(
+            script: "docker images -q ${DOCKERHUB_USER}/${IMAGE_NAME}:${params.IMAGE_TAG}",
+            returnStdout: true
+          ).trim()
+
+          if (imageExists) {
+            echo "✅ Docker image ${DOCKERHUB_USER}/${IMAGE_NAME}:${params.IMAGE_TAG} already exists locally. Skipping build."
+          } else {
+            sh """
+              echo "Using existing WAR file..."
+              WAR_FILE="taxi-booking/target/taxi-booking-1.0.1.war"
+              echo "Building Docker image..."
+              cp \$WAR_FILE ./ || { echo "WAR file not found!"; exit 1; }
+              docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${params.IMAGE_TAG} .
+            """
+          }
         }
       }
     }
